development:
  adapter: postgresql
  encoding: unicode
  database: malohka_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: malohka_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: malohka
  pool: 5
  username: postgres
  password: malohka
  host: localhost